<?php

namespace AppBundle\Repository;

/**
 * MusicAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicAppRepository extends \Doctrine\ORM\EntityRepository
{
    
    // THIS FUNCTION RETURNS the number of songs per page in the pagination component.
    public function paginationElements($pageNum = 1 , $numMaxSongs){

        //var_dump("var dump = ".$numMaxSongs);
        
        $query = $this->createQueryBuilder('s')
        ->where('s.topFavorite = 1')
        ->setFirstResult($numMaxSongs*($pageNum-1))
        ->setMaxResults($numMaxSongs)
        ->getQuery();

        return $query->getResult();
      
    }



  
    public function findAllWithSearch($term)
    {

        
        if ($term) {
            $qb = $this->createQueryBuilder();
            $posts = $qb->select('p')
                ->from(MusicApp::getClassName(), 'p')
                ->where($qb->expr()->like('p.trackName', ':term')
                ->andWhere($qb-expr()->like('p.artistName', ':term')
                ->andWhere($qb-expr()->like('p.albumName', ':term')
           
                ->setParameter('term', '%' . $term . '%')
             ;
        }else{
            die();
        }
        return $qb
            ->orderBy('c.creationDate', 'DESC')
            ->getQuery()
            ->getResult()
        ;
       }

   }
